version: '3.7'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   environment:
  #     - REDIS_HOST=hogwartsredis
  #     - RABBITMQ_USER=guest
  #     - RABBITMQ_PASS=guest
  #     - RABBITMQ_HOST=hogwartsmq
  #   tty: true
  
  hogwartsmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    tty: true

  hogwartsredis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    tty: true